source 'https://rubygems.org'

ruby '2.1.2'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'travis'
gem 'faye-websocket'
gem 'sinatra-cross_origin'
gem 'rspec'
gem 'sinatra-assetpack'
gem 'sinatra-activerecord'
gem 'rake'
gem 'therubyracer'
gem 'less'
gem 'thin'
