source 'https://rubygems.org'

ruby '2.1.2'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'travis'
gem 'jenkins_api_client', '~> 1.0.1'
gem 'faye-websocket'
gem 'sinatra-cross_origin'
gem 'rspec'
gem 'sinatra-assetpack'
gem 'sinatra-activerecord'
gem 'rake'
gem 'therubyracer'
gem 'less'
gem 'thin'
gem 'events'
gem 'rufus-scheduler', '~> 3.0.9'
